### ISSUE TITLE
Autoscroll extension doesn't seem to work

### ISSUE THREAD

**Issue by kukanya** [ipython-contrib/Jupyter-notebook-extensions#672]
I'm not sure if I understand what it is supposed to do correctly, but it doesn't seem to do anything at all for me.
I've thought it scrolls the output down if there are more than `threshold` lines, am I right? :)

Here's how the output looks like right after running the cell:
![image](https://cloud.githubusercontent.com/assets/16195289/16985975/b1d4fdea-4e8c-11e6-9831-253fcd6fe0ea.png)

`jupyter --version` returns `4.1.0`
`jupyter notebook --version` returns `4.2.1`
(if this information is relevant).

**Comment by juhasch** [comment]
You are right, this is a bug. Should be fixed by #674.

**Comment by kukanya** [comment]
Still doesn't work for me.
I've noticed that default behaviour is auto-scrolling exactly as far down as the output was scrolled before the cell was executed again.
Turning the extension on and adjusting it's threshold doesn't change this behaviour.

**Comment by juhasch** [comment]
True, it only worked for newly executed cells. I have changed this now in the PR.
Can you tetst it if it now works as desired ?

**Comment by juhasch** [comment]
Fixed by #683 after restructuring
